### PR TITLE
Update to work with npm

### PR DESCRIPTION
**Pull request by keegnotrub**
jeffwatkins updated the package.json include npm's main dictionary key.  This is just that patch along with your change to remove the comma from the last contributor.

### CODE REVIEW

**Comment by tommoor** [comment]
Any chance of this getting merged? The current broken release on npm isn't doing anyone any favours...

**Comment by arunoda** [comment]
please accpet the pull request

**Comment by alexanderdean** [comment]
Yeah I'm waiting on this too

**Comment by damselem** [comment]
+1

**Pull request closed without merging**
